"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import secrets
from . import shared_settings as shared_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.token_hex(16)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("debug"))

ALLOWED_HOSTS = [os.environ["allowed_host"]]

from .adding_www import adding_www

custom_allowed_origin = os.environ["allowed_origin"]
CORS_ALLOWED_ORIGINS = [
    custom_allowed_origin,
    adding_www(custom_allowed_origin),
    "https://localhost:8080",
    "https://localhost:8000",
    "https://localhost",
    "http://localhost:8080",
    "http://localhost:8000",
    "http://localhost",
    # "http://localhost:45678", # experiment with react-snap
]

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "worker.apps.WorkerConfig",
    "rest_framework",
    # "django_celery_results",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

from .celery import REDIS_HOST_RESULT, REDIS_RESULT_PASSWORD



# django setting.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST_RESULT}:{shared_settings.REDIS_RESULT_PORT}/0",
        "OPTIONS": {
            "PASSWORD": REDIS_RESULT_PASSWORD,
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
    }
}

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

import logging
logging.basicConfig(format='%(levelname)s: %(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p', level=logging.INFO)
logging.info("init logging")


TEST_PRIVATE_KEY=r"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmn8+4Wwm1k2cl\nfBcAUIoIX2uGluvdIIUr7vQA4cnRJ2EkQ4mGN81eaW16o4OS2ExV7aX3ymWpc8rk\nggjItM7/mKePlZ9C8j5iKVkSQR4x513OWRKqtduFM6iZjIsQoPAU6dAM8c1OS129\ngsGeW/9IBFWr0gMd7Aor47qUWSvywoU5qyFVf2a1iMhiSW8c24L8Iwle5V0Rmc6V\nZ40nG6TTiZqkBvWF90QUgP/AbYiuTep96/dXDyTRlpcfuwuuEPqW9M81BJm5pgnF\nQoqW1AR9jsVhDE6Dv910L6uvUKYJxeGgbVPw6IrRWZvmDCbh/116JtOgEawnLaU+\n1u+uGct3AgMBAAECggEANGzb4llieKrkLTsZ0ZOFmpTLNBGQLIbq36PTSePAp/oH\n6m0FfCFakHYDaC7CWxWLDw4yxf/8dJBmKfdv5BZferQBJIAjF+E4F5KC3+d1JKZz\nMVV9NhD5/LMAPS+nIZhBcZMPTsNVoWi9Gb9mQ/kWHQagHet555Q4rw57yek0lrBz\nHsUlzpkxrsTMjgy50O3U7em5o5dukvCxoKIhrBcR4P7IDuGaKoZjWSDER8F05/Ra\nQwtXtnf/86F8slRsLEnO71e1O6f/lNFMWhJOsCngzD+dp8GJzBbLDp/kTqSNYNYV\nv9pP2S5+K8Wsd7R+vsAPGVmnF6YeWmfGNHg7OUQW4QKBgQDbXs0ipyBVQ9HUCf3+\nuczFSlIkYe7BZnyc1//txY1aNQ4Qt4lsY4YPei3RY939EyKo3rMJ5SDrMv2S3P8O\nTcBvHEmQmRgyi5TFRtBx5hgHGJIu5IRt9PSeQ9GiRS2ZU8tiAK7/siBGXoK8gAfy\nr8DtfiyP+fUPdMJQrAD4ecHuJQKBgQDCclQUlacfQBKvlFF/z5H4fu4/2b2e3e0E\nO/4Qun0VoWeDMvAjoHlG4kgW3ZtbOCFYrAPOYn1dxud56KLhTyg66l9OdWvXZxEa\no095P9lTxwLrtjJXrFWpS75KyTnkqs/CJSGBPnSMOsZIdoqawS6F6q+341QCJZry\nfbMoTNWaawKBgE4a9OLPqn1xRjY+0IZvVO8xxQlbLQ0DFn8pkN/xpKBnn3hoQK+s\nx8Ce+c1Bx3oh5AdIM2rkf9H+N7agpNdM66Uj5zVqrOjiNbf/vJuxFwD/yJyVlGkp\n/CaVcwBZrSCYayObprM3krI7WEUROMM5vHFSqT8h+hTkt4LNmxLdFyVZAoGBAJs2\nGYmI36shQQkoMln8fX9HCrSrASKD8YLUxHvj8J7IhNEEYw19NfFwBK1D3ZPV3UBj\npnIiygGGGRWFriZ9QhatKMB/GEMLwWpq+7BEWBz4mYs/lzXGmWYW0OHveCfgdRB7\nBSCekvewnsAO55qaI6G/8N2vN0qza9iun8jGdCbbAoGAX4FZ+q4P3hzJhjKf/0JX\nVTaIW4TtIDmar02H0n8a+z1Ol4qOqEr53TtG5lNwjL49ZV+07csC4KvdWTrVIcfg\n+et0jJu3g87JRDD1/rHXWGViaVCV3O7Nc1TK921ENV/cc3ow/bJ/9c/U9dKiHUe2\nkxMgQs/uB8PBfxZJb6VTFNU=\n-----END PRIVATE KEY-----\n"