version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
