version: '3.8'
services:
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
  dind:
    image: docker:20.10.21-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    expose:
      - 2375
  app:
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_RESULT_HOST: redis
      DOCKER_HOST: tcp://dind:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
