x-definitions:
  x-backend-app:
    &x-backend-app
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    depends_on:
      - redis
  x-env-args:
    &x-env-args
    REDIS_QUEUE_HOST: redis
    REDIS_RESULT_HOST: redis
    INSTALLER_NETWORK: shapevpn
    test_redis_host: redis

version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    <<: *x-backend-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    environment:
      <<: *x-env-args
  beat:
    <<: *x-backend-app
    environment:
      <<: *x-env-args
    command: celery -A backend_api.src.core.celery beat
  worker:
    <<: *x-backend-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *x-env-args
    command: celery -A backend_api.src.core.celery worker

networks:
  default:
    name: shapevpn
    driver: bridge
