version: "3"

tasks:
  format:installer:
    cmds:
      - mypy server_installer
      - black server_installer
      - isort --profile black server_installer

  format:handler:
    cmds:
      - black job_handler
      - isort --profile black job_handler
      - mypy job_handler

  format:
    cmds:
      - task: format:installer
      - task: format:handler
