version: "3"

tasks:
  prod:deploy:
    cmds:
      - ansible-playbook -i hosts.prod.yml deploy.yml

  prod:download:
    cmds:
      - ansible-playbook -i hosts.prod.yml download.yml

  staging:deploy:
    cmds:
      - ansible-playbook -i hosts.staging.yml deploy.yml

  staging:download:
    cmds:
      - ansible-playbook -i hosts.staging.yml download.yml

  install:
    cmds:
      - ansible-galaxy collection install community.general
