apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      volumes:
      containers:
        - name: redis-ctr
          image: redis:latest
          resources:
            requests:
              memory: "{{.Values.soft_memory_limit}}"
              cpu: "{{.Values.soft_cpu_limit}}"
            limits:
              memory: "{{.Values.hard_memory_limit}}"
              cpu: "{{.Values.hard_cpu_limit}}"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis-app