apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkbot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkbot-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: darkbot-app
        triggerRedeploy: "1"
    spec:
      volumes:
        - name: darkbot-persistent-storage
          hostPath:
            path: /var/lib/darklab/darkbot
            type: DirectoryOrCreate
      containers:
        - name: darkbot-ctr
          image: darkwind8/darkbot:{{ .Values.image_version }}
          imagePullPolicy: Always
          env:
            - name: SCRAPPY_PLAYER_URL
              value: "{{ .Values.SCRAPPY_PLAYER_URL }}"
            - name: SCRAPPY_BASE_URL
              value: "{{ .Values.SCRAPPY_BASE_URL }}"
            - name: DISCORDER_BOT_TOKEN
              value: "{{ .Values.DISCORDER_BOT_TOKEN }}"
            - name: CONFIGURATOR_DBNAME
              value: "{{ .Values.CONFIGURATOR_DBNAME }}"
            - name: CONSOLER_PREFIX
              value: "{{ .Values.CONSOLER_PREFIX }}"
            - name: LOGGING
              value: "{{ .Values.LOGGING }}"
            - name: LOOP_DELAY
              value: "{{ .Values.LOOP_DELAY }}"
          volumeMounts:
            - mountPath: "/code/data"
              name: darkbot-persistent-storage
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "{{.Values.hard_memory_limit}}Mi"
              cpu: "{{.Values.hard_cpu_limit}}m"
