version: "3"

tasks:
  # 1860 and 405 grafana imported dashboards
  grafana:connect:
    cmds:
      - kubectl port-forward service/loki-grafana 5000:80

  grafana:password:
    cmds:
      - kubectl get secret --namespace loki loki-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
