FROM docker:20.10.12-dind

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apk add --update make
RUN apk add --update python3 py3-pip py3-virtualenv
    # apt-get install build-essential libssl-dev libffi-dev python-dev
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev

WORKDIR /app

COPY ./requirements.txt ./
COPY ./constraints.txt ./
RUN python3 -m venv venv
RUN venv/bin/pip3 install -r requirements.txt -c constraints.txt

COPY manage.py pytest.ini makefile ./
COPY core core
COPY worker worker

RUN chmod 777 /app

CMD venv/bin/celery -A core worker -l INFO
