version: "3"

tasks:
  check:
    cmds:
      - echo "$(cat private.key)"

  build:
    cmds:
      - docker build --tag test .

  push:
    cmds:
      - docker tag test darkwind8/shapevpn:installer-latest
      - docker push darkwind8/shapevpn:installer-latest

  integration1:
    cmds:
      - sudo rm -R configs | true
      - docker run -v $(pwd)/configs:/app/configs test install --user="root" --ip="shapevpn-installer-test-subject.light-search.com" --auth="ssh" --private_key="$(cat private.abc.key)"
