apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dind-app
    spec:
      volumes:
      containers:
        - name: dind-pod
          image: docker:20.10.12-dind
          ports:
            - containerPort: 2375
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args:
            - "--mtu=1440" # https://liejuntao001.medium.com/fix-docker-in-docker-network-issue-in-kubernetes-cc18c229d9e5 because this
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "{{.Values.soft_memory_limit}}"
              cpu: "{{.Values.soft_cpu_limit}}"
            limits:
              memory: "{{.Values.hard_memory_limit}}"
              cpu: "{{.Values.hard_cpu_limit}}"
---
apiVersion: v1
kind: Service
metadata:
  name: dind-service
spec:
  type: ClusterIP
  ports:
    - name: dind
      port: 2375
      targetPort: 2375
  selector:
    app: dind-app