all:
  vars:
    ansible_user: root
    ansible_connection: ssh
    ansible_ssh_extra_args: "-o ForwardAgent=yes"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.darklab

  children:
    cluster:
      hosts: 1.2.3.4
      vars:
        varenv: prod
        app: shapevpn
