version: "3"
tasks:
  init:
    env:
      FOLDER: roles/install_dockered_wireguard/files
    cmds:
      - curl -o $FOLDER/docker-ce.deb https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb
      - curl -o $FOLDER/docker-ce-cli.deb https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb
      - curl -o $FOLDER/containerd.deb https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.4.9-1_amd64.deb

    status:
      - test -f $FOLDER/docker-ce.deb
      - test -f $FOLDER/docker-ce-cli.deb
      - test -f $FOLDER/containerd.deb

  run:
    cmds:
      - echo "getting started"
      - task: init
      - ansible-playbook -i hosts.yml install_dockered_requirements.yml --key-file=~/.ssh/id_rsa.shapevpn.test_installer
      - ansible-playbook -i hosts2.yml install_dockered_wireguard.yml -key-file=~/.ssh/id_rsa.shapevpn.test_installer
      - ansible-playbook -i hosts.yml download_configs.yml -key-file=~/.ssh/id_rsa.shapevpn.test_installer
