version: "3"

tasks:
  hetzner_images:
    cmds:
      - curl -H "Authorization: Bearer $TF_VAR_staging_hcloud_token" 'https://api.hetzner.cloud/v1/images' > hetzner_images.json

  installer:format:
    cmds:
      - mypy server_installer
      - black server_installer
      - isort --profile black server_installer

  backend:format:
    cmds:
      - black backend
      - isort --profile black backend
      - mypy backend

  format:
    cmds:
      - task: installer:format
      - task: backend:format

  build:
    cmds:
      - docker-compose -p shapevpn build -- worker
      - docker tag shapevpn_worker shapevpn_beat
      - docker tag shapevpn_worker shapevpn_backend
      - docker-compose -p shapevpn build -- frontend

      - docker build --tag darkwind8/shapevpn:installer-latest server_installer
      - docker tag shapevpn_worker darkwind8/shapevpn:backend-latest
      - docker tag shapevpn_frontend darkwind8/shapevpn:frontend-latest

  push:
    cmds:
      - docker push darkwind8/shapevpn:installer-latest
      - docker push darkwind8/shapevpn:backend-latest
      - docker push darkwind8/shapevpn:frontend-latest
