---
- name: install_docker_packages
  include_role:
    name: install_dockered_wireguard
    tasks_from: install_docker_packages

- name: install_docker_py
  include_role:
    name: install_dockered_wireguard
    tasks_from: install_docker_py