---
- name: Create a docker_py directory if it does not exist
  ansible.builtin.file:
    path: "/docker_py"
    state: directory

- name: Copy docker-py tar
  ansible.builtin.copy:
    src: docker_py/docker_py.tar.gz
    dest: /docker_py/docker_py.tar.gz

- name: Extracting
  shell: tar zxvf docker_py.tar.gz -C .
  args:
    chdir: /docker_py
    creates: /docker_py/venv