name: CI backend

on:
  pull_request: {}
  workflow_call: {}
  push: {}

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install requirements
        run: |
          pip install -r backend_api/requirements.txt -r backend_api/requirements.dev.txt -c server_installer/constraints.txt
      - name: Black
        run: black --check backend_api
      - name: Mypy
        run: mypy backend_api
      - name: Isort
        run: isort --check --profile black backend_api
  unit-tests: # build, push, pull, test?
    runs-on: ubuntu-22.04
    services:
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: backend_api/Dockerfile
          load: true
          tags: darkwind8/shapevpn:backend-latest

      - name: Test
        run: |
          docker run --rm darkwind8/shapevpn:backend-latest pytest backend_api
