name: CI backend

on:
  pull_request: {}
  workflow_call: {}
  push: {}

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install requirements
        run: |
          pip install -r backend_api/requirements.txt -r backend_api/requirements.dev.txt -c server_installer/constraints.txt
      - name: Black
        run: black --check backend_api
      - name: Mypy
        run: mypy backend_api
      - name: Isort
        run: isort --check --profile black backend_api
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build server_installer_too
        uses: docker/build-push-action@v4
        with:
          context: server_installer
          load: true
          tags: server_installer_autouse
      - name: Build Backend
        run: |
          docker-compose -p shapevpn build -- worker
          docker tag shapevpn_worker shapevpn_beat
          docker tag shapevpn_worker shapevpn_backend
      - uses: webiny/action-post-run@2.0.1
        with:
          run: |
            docker-compose -p shapevpn down --volumes --rmi local
      - name: Test Backend
        run: |
          docker-compose -p shapevpn up -d redis worker beat
          sleep 5
          docker-compose -p shapevpn run backend pytest backend_api
      - name: Build frontend
        run: |
          docker-compose -p shapevpn up -d backend
          docker-compose -p shapevpn build -- frontend
      - name: Test frontend
        run: |
          docker-compose -p shapevpn run frontend npm run test:unit
